#!/usr/bin/env bash

Number=1000
echo Can you guess the number? Try it..Enter
read guess
  if [ $Number -eq $guess ]
  then
    echo Yes right!!
  else
    echo OOPS! Wrong
  fi


#Another one to check file exists or not
#clear
if [ -e /home/ameer/gcloudtechie.online/Linux/03-basic-shell-scripts/scripts/error.txt ]
then
  echo File is there
else
  echo OOPS! File is not there
fi
